# Generated by Django 5.1.6 on 2025-02-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidades_vendidas',
            field=models.IntegerField(default=0),
        ),
    ]
