# Generated by Django 5.1.6 on 2025-04-11 18:26

import apps.productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, validators=[apps.productos.models.validar_positivo]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(validators=[apps.productos.models.validar_positivo]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(validators=[apps.productos.models.validar_positivo]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidades_vendidas',
            field=models.IntegerField(default=0, validators=[apps.productos.models.validar_positivo]),
        ),
    ]
