# Generated by Django 5.1.6 on 2025-04-11 18:48

import apps.productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_producto_costo_alter_producto_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='porcentaje_ganancia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True, validators=[apps.productos.models.validar_positivo]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[apps.productos.models.validar_positivo]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(null=True, validators=[apps.productos.models.validar_positivo]),
        ),
    ]
