# Generated by Django 5.1.6 on 2025-04-15 02:11

import apps.productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_categoria_porcentaje_ganancia_alter_producto_costo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, validators=[apps.productos.models.validar_positivo]),
        ),
    ]
