# Generated by Django 5.1.6 on 2025-06-03 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_alter_producto_imagen_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
    ]
