# Generated by Django 5.1.6 on 2025-02-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=10, unique=True)),
                ('ciudad', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=10, unique=True)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
    ]
