# Generated by Django 5.1.6 on 2025-02-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='imagen',
            field=models.ImageField(default=1, upload_to='clientes/'),
            preserve_default=False,
        ),
    ]
