# Generated by Django 5.1.6 on 2025-05-22

import django.db.models.deletion
from django.db import migrations, models

def convertir_ciudades(apps, schema_editor):
    Cliente = apps.get_model('clientes', 'Cliente')
    Ciudad = apps.get_model('clientes', 'Ciudad')
    for cliente in Cliente.objects.all():
        try:
            ciudad = Ciudad.objects.get(nombre_ciudad=cliente.ciudad)
            cliente.ciudad = ciudad
            cliente.save()
        except:
            pass  # ignora errores si algún nombre no existe

class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_pais_alter_cliente_ciudad_provincia_ciudad'),
    ]

    operations = [
    migrations.RunPython(convertir_ciudades),
    migrations.AlterField(
        model_name='cliente',
        name='ciudad',
        field=models.ForeignKey(
            null=True,
            on_delete=django.db.models.deletion.CASCADE,
            to='clientes.Ciudad'
        ),
    ),
    ]

