# Generated by Django 5.1.6 on 2025-05-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_cliente_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
