# Generated by Django 5.1.6 on 2025-06-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_alter_cliente_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
    ]
