# Generated by Django 5.1.6 on 2025-06-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_alter_cliente_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='imagen',
            field=models.ImageField(blank=True, default='clientes/cliente.png', null=True, upload_to='clientes/'),
        ),
    ]
