# Generated by Django 5.1.6 on 2026-04-03 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=100)),
                ('nombre_comercial', models.CharField(max_length=100)),
                ('ruc', models.CharField(max_length=13, unique=True)),
                ('direccion', models.TextField(help_text='Av. 5 de octubre')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('password_correo', models.EmailField(max_length=255)),
                ('archivo_p12', models.FileField(blank=True, null=True, upload_to='firmas/')),
                ('password_p12_encriptada', models.CharField(blank=True, max_length=255, null=True)),
                ('ambiente_sri', models.CharField(choices=[('1', 'Pruebas'), ('2', 'Producción')], default='1', max_length=1)),
                ('contador_secuencial', models.PositiveIntegerField(default=1)),
                ('cod_establecimiento', models.CharField(default='001', help_text='Ej: 001', max_length=3)),
                ('cod_punto_emision', models.CharField(default='001', help_text='Ej: 001', max_length=3)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_vencimiento_plan', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
