# Generated by Django 5.1.6 on 2026-04-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='password_correo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
