# Generated by Django 5.1.6 on 2026-04-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_alter_empresa_password_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='password_correo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
