# Generated by Django 5.1.6 on 2025-06-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEnvioCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_ejecucion', models.DateField(blank=True, null=True)),
                ('exito', models.BooleanField(default=False)),
            ],
        ),
    ]
