# Generated by Django 5.1.6 on 2026-04-03 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.CharField(max_length=300)),
                ('telefono', models.CharField(max_length=10)),
                ('ruc', models.CharField(max_length=13, unique=True)),
                ('imagen', models.ImageField(upload_to='proveedores/')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.ciudad')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
        ),
    ]
