# Generated by Django 5.1.6 on 2025-02-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='ciudad',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='ruc',
            field=models.CharField(default=2, max_length=13, unique=True),
            preserve_default=False,
        ),
    ]
