# Generated by Django 5.1.6 on 2025-02-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_proveedor_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='imagen',
            field=models.ImageField(default=1, upload_to='proveedores/'),
            preserve_default=False,
        ),
    ]
