# Generated by Django 5.1.6 on 2025-05-22 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_alter_cliente_ciudad'),
        ('proveedores', '0004_alter_proveedor_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.ciudad'),
        ),
    ]
