# Generated by Django 5.1.6 on 2025-05-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cedula',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
