# Generated by Django 5.1.6 on 2026-04-03 02:51

import apps.creditos.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[apps.creditos.models.validar_positivo])),
                ('cuota', models.IntegerField(validators=[apps.creditos.models.validar_positivo])),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia')], default='EFECTIVO', max_length=13)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='PlazoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meses', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montoInicial', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[apps.creditos.models.validar_positivo])),
                ('montoTotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[apps.creditos.models.validar_positivo])),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cuotas', models.IntegerField(null=True, validators=[apps.creditos.models.validar_positivo])),
                ('montoCuota', models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[apps.creditos.models.validar_positivo])),
                ('tipo_pago', models.CharField(choices=[('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual')], max_length=7)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('MOROSO', 'Moroso'), ('FINALIZADO', 'Finalizado')], default='ACTIVO', max_length=10)),
                ('cuotas_pagadas', models.IntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
        ),
    ]
