# Generated by Django 5.1.6 on 2025-02-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0002_alter_pago_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('FINALIZADO', 'FINALIZADO')], default='NINGUNO', max_length=10),
        ),
    ]
