# Generated by Django 5.1.6 on 2025-02-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0003_alter_credito_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='tipo_pago',
            field=models.CharField(choices=[('SEMANAL', 'SEMANAL'), ('MENSUAL', 'MENSUAL')], default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credito',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('FINALIZADO', 'FINALIZADO')], max_length=10),
        ),
    ]
