# Generated by Django 5.1.6 on 2025-02-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0004_credito_tipo_pago_alter_credito_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credito',
            old_name='monto',
            new_name='montoCuota',
        ),
        migrations.AddField(
            model_name='credito',
            name='montoTotal',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
