# Generated by Django 5.1.6 on 2025-02-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0005_rename_monto_credito_montocuota_credito_montototal'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='cuota',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'EFECTIVO'), ('TRANSFERENCIA', 'TRANSFERENCIA')], default='EFECTIVO', max_length=13),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
