# Generated by Django 5.1.6 on 2025-04-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0006_pago_comentarios_pago_cuota_pago_metodo_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='montoCuota',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
