# Generated by Django 5.1.6 on 2025-04-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0007_alter_credito_montocuota_alter_pago_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='montoTotal',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
