# Generated by Django 5.1.6 on 2025-04-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0008_alter_credito_montototal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='cuotas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='credito',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('FINALIZADO', 'FINALIZADO')], default='ACTIVO', max_length=10),
        ),
        migrations.AlterField(
            model_name='credito',
            name='montoCuota',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
