# Generated by Django 5.1.6 on 2025-04-11 18:26

import apps.creditos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0009_alter_credito_cuotas_alter_credito_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='cuotas',
            field=models.IntegerField(null=True, validators=[apps.creditos.models.validar_positivo]),
        ),
        migrations.AlterField(
            model_name='credito',
            name='montoCuota',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[apps.creditos.models.validar_positivo]),
        ),
        migrations.AlterField(
            model_name='credito',
            name='montoTotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[apps.creditos.models.validar_positivo]),
        ),
        migrations.AlterField(
            model_name='pago',
            name='cuota',
            field=models.IntegerField(validators=[apps.creditos.models.validar_positivo]),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[apps.creditos.models.validar_positivo]),
        ),
    ]
