# Generated by Django 5.1.6 on 2025-04-14 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0010_alter_credito_cuotas_alter_credito_montocuota_and_more'),
        ('ventas', '0006_alter_detalleventa_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='venta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.venta'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('MOROSO', 'Moroso'), ('FINALIZADO', 'Finalizado')], default='ACTIVO', max_length=10),
        ),
        migrations.AlterField(
            model_name='credito',
            name='tipo_pago',
            field=models.CharField(choices=[('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual')], max_length=7),
        ),
    ]
