# Generated by Django 5.1.6 on 2025-04-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0011_credito_venta_alter_credito_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='cuotas_pagadas',
            field=models.IntegerField(default=0),
        ),
    ]
