# Generated by Django 5.1.6 on 2025-04-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0012_credito_cuotas_pagadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia')], default='EFECTIVO', max_length=13),
        ),
    ]
