# Generated by Django 5.1.6 on 2025-06-18 19:55

import apps.creditos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0014_credito_usuario_pago_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='montoInicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[apps.creditos.models.validar_positivo]),
        ),
    ]
