# Generated by Django 5.1.6 on 2025-06-20 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0015_credito_montoinicial'),
        ('productos', '0013_remove_producto_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlazoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meses', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_credito', to='productos.producto')),
                ('plazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditos.plazocredito')),
            ],
        ),
    ]
