# Generated by Django 5.1.6 on 2025-02-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_venta_fecha_alter_venta_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
