# Generated by Django 5.1.6 on 2025-04-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_venta_fecha_alter_venta_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Credito', 'Credito'), ('Tarjeta de Credito', 'Tarjeta de Credito'), ('Tarjeta de Debito', 'Tarjeta de Debito')], default='CONTADO', max_length=20),
        ),
    ]
