# Generated by Django 5.1.6 on 2025-04-11 17:57

import apps.ventas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_detalleventa_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.IntegerField(default=1, validators=[apps.ventas.models.validar_positivo]),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[apps.ventas.models.validar_positivo]),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='total_cantidad_producto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[apps.ventas.models.validar_positivo]),
        ),
        migrations.AlterField(
            model_name='venta',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[apps.ventas.models.validar_positivo]),
        ),
        migrations.AlterField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[apps.ventas.models.validar_positivo]),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[apps.ventas.models.validar_positivo]),
        ),
    ]
