# Generated by Django 5.1.6 on 2025-04-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_detalleventa_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Credito', 'Credito'), ('Tarjeta de Credito', 'Tarjeta de Credito'), ('Tarjeta de Debito', 'Tarjeta de Debito')], default='Efectivo', max_length=20),
        ),
    ]
