# Generated by Django 5.1.6 on 2025-05-09 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_alter_venta_metodo_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleventa',
            old_name='total_cantidad_producto',
            new_name='subtotal',
        ),
    ]
