# Generated by Django 5.1.6 on 2025-05-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_rename_total_cantidad_producto_detalleventa_subtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_metodo', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Credito', 'Credito'), ('Tarjeta de Credito', 'Tarjeta de Credito'), ('Tarjeta de Debito', 'Tarjeta de Debito')], default=('Efectivo', 'Efectivo'), max_length=25),
        ),
    ]
