# Generated by Django 5.1.6 on 2025-07-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_alter_venta_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='paypal_datos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
